### ISSUE TITLE
Show smileys

### ISSUE THREAD

**Issue by kozuch** [andreas-mausch/whatsapp-viewer#94] opened 2019-11-16 00:52 UTC
Is there a way to also show smileys in the chats? I have a rooted phone so I have a access to whole /data/data/com.whatsapp directory... Interestingly very very few smileys do show from the .db file, I could not find out rule for this (seems to be random).

**Comment by andreas-mausch** [comment] 2020-09-20 21:41
Duplicate of #72

**Closed by andreas-mausch** 2020-09-20 21:41 UTC
