### ISSUE TITLE
Run time error when decrypting file > 150mb

### ISSUE THREAD

**Issue by alloyion** [andreas-mausch/whatsapp-viewer#93] opened 2019-09-25 16:01 UTC
Hi Andreas, 
I been using your whatsapp viewer to decrypt and viewer my whatsapp messages.
Since my whatsapp have daily backup .. the viewer having problem when the encrypted db bigger than 150mb. Here is the error screenshot
![Screenshot 2019-09-25 23 55 46](https://user-images.githubusercontent.com/31270070/65618237-88191100-dff0-11e9-81eb-0b0a6ab5d0bc.png)
The message db size : 177mb

**Comment by pweasel** [comment] 2019-10-01 22:44
yep, mine is 159 MB and also gives me RT error on decrypting.

**Comment by andreas-mausch** [comment] 2019-10-02 08:06
Sorry guys. I close this one as it's a duplicate of #46.

**Closed by andreas-mausch** 2019-10-02 08:06 UTC
